sudo: false
language: python
python:
- "2.7"
install:
- pip install -r requirements.txt
script:
- mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: site
  on:
    branch: master
